#!/bin/sh
# 
# Sets the wallpaper greping the image on the given directory.
#
# Usage:
# set-wallpaper <directory>

dir=$1

# filters an image (a file ending in .png, .jpg or .jpeg) from the contents of
# the given dir.
filename=$(ls -1 $dir | grep -E -e '.*\.(jpeg|jpg|png)')
echo wallpaper file: ${dir}/${filename}

# --bg-center centers the image and
#  if too small, uses black borders around
#  if too big, the image is cut and only the very center is seen
#  the aspect ratio is kept
feh --bg-center ${dir}/${filename}

