#!/bin/bash
if synclient -l | grep "TouchpadOff .*=.*0" ; then
    synclient TouchpadOff=1 ;
    notify-send --expire-time=100 'Touchpad disabled'
else
    synclient TouchpadOff=0 ;
    notify-send --expire-time=100 'Touchpad enabled'
fi

